#オートセーブをするかしないか(する場合:true しない場合:false)
autoSave: true

#オートセーブをする間隔(標準30分毎)
#分単位で指定してください。(小数点を利用した指定はできません。)
saveInterval: 30

#オートバックアップをするかしないか
autoBackup: true

#オートバックアップをする感覚(標準3時間毎)
#分単位で指定してください。(小数点を利用した指定はできません。)
backupInterval: 180