name: AutoSaveBackup
version: 1.0.2
main: com.gmail.rotoyutoriapp.AutoSaveBackup
api-version: 1.17
author: rito528 (528.rito@gmail.com)
commands:
  asb:
    usage: /asb <args>

permissions:
  asb.*:
    default: op
    children:
      asb.save: true
      asb.backup: true
      asb.help: true
  asb.save:
    default: op
    children:
      asb.help: true
  asb.backup:
    default: op
    children:
      asb.help: true
  asb.reload:
    default: op
    children:
      asb.help: true
  asb.help:
    default: op