#オートセーブをするかしないか(する場合:true しない場合:false)
autoSave: true

#オートセーブをする間隔(標準30分毎)
#分単位で指定してください。(小数点を利用した指定はできません。)
saveInterval: 30

#オートバックアップをするかしないか
autoBackup: true

#オートバックアップをする感覚(標準3時間毎)
#分単位で指定してください。(小数点を利用した指定はできません。)
backupInterval: 180

#バックアップをするワールドを指定してください。('*'ですべてのワールドをバックアップします。
#  ※すべて指定する場合はシングルクォーテーションでくくってください。)
#初期状態では、すべてのワールドをバックアップします。
#以下の例では、初期で生成されるワールドと、エンドのバックアップを作成します。
#例)
#backupWorlds:
# - world
# - world_the_end
backupWorlds:
  - '*'

#バックアップを一定日数で自動削除するか
isAutoBackupDelete: false

#何日前以降のバックアップを削除するか
deleteTargetDay: 20

#定期再起動をするか
restart: false

#定期再起動をする場合は再起動を行う時間を指定してください。(午前4時 -> 04:00、午後4時 -> 16:00というように指定してください。)
#また、この機能を利用するにはSpigot標準機能の/restartコマンドが使える状態である必要があります。
restartTime:
  - 04:00