name: AutoSaveBackup
version: 1.0.0
main: com.gmail.rotoyutoriapp.AutoSaveBackup
api-version: 1.17
author: rito528 (528.rito@gmail.com)
commands:
  asb:
    permission: asb.asb
    permission-message: 'あなたは権限を持っていません！'
    usage: /asb <args>

permissions:
  asb.asb:
    default: op